<?php

return [
    'locations' => [
        'Dubai Land' => [
            'name' => 'Dubai Land',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '23',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Jebel Ali' => [
            'name' => 'Jebel Ali',
            'image' => "frontend/img/real-estate/city/chicago.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Production City' => [
            'name' => 'Dubai Production City',
            'image' => "frontend/img/real-estate/city/dallas.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Al Satwa' => [
            'name' => 'Al Satwa',
            'image' => "frontend/img/real-estate/city/san-diego.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Palm Jumeirah' => [
            'name' => 'Palm Jumeirah',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Jebel Ali' => [
            'name' => 'Jebel Ali',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'JVC' => [
            'name' => 'JVC',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'JVT' => [
            'name' => 'JVT',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Arjan' => [
            'name' => 'Arjan',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Industrial City' => [
            'name' => 'Dubai Industrial City',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai South' => [
            'name' => 'Dubai South',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Studio City' => [
            'name' => 'Dubai Studio City',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Hills' => [
            'name' => 'Dubai Hills',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Jumeirah Central' => [
            'name' => 'Jumeirah Central',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Barsha Heights' => [
            'name' => 'Barsha Heights',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Harbour' => [
            'name' => 'Dubai Harbour',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Nad Al Sheba' => [
            'name' => 'Nad Al Sheba',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Marina' => [
            'name' => 'Dubai Marina',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Business Bay' => [
            'name' => 'Business Bay',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],

        'Downtown Dubai' => [
            'name' => 'Downtown Dubai',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'DIFC' => [
            'name' => 'DIFC',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'City Walk' => [
            'name' => 'City Walk',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Jumeirah Bay' => [
            'name' => 'Jumeirah Bay',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'La Mer' => [
            'name' => 'La Mer',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Dubai Design District' => [
            'name' => 'Dubai Design District',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],

        'Dubai Creek harbour' => [
            'name' => 'Dubai Creek harbour',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Jumeirah Garden City' => [
            'name' => 'Jumeirah Garden City',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Pearl Jumeirah' => [
            'name' => 'Pearl Jumeirah',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'JBR' => [
            'name' => 'JBR',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
        'Bluewaters' => [
            'name' => 'Bluewaters',
            'image' => "frontend/img/real-estate/city/new-york.jpg",
            'for_sale' => '1',
            'for_sale_percentage'=>'85',
            'for_rent_percentage'=>'89',
            'for_rent' => '1',
        ],
    ],
];
